//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for AirItineraryPricingInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AirItineraryPricingInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pricingSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pricingSubSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fareReturned" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="privateFareType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="itinTotalFare" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}ItinTotalFare" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pTC_FareBreakdowns" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}PTC_FareBreakdowns" minOccurs="0"/>
 *         &lt;element name="divideInPartyInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AirItineraryPricingInfo", propOrder = {
    "pricingSource",
    "pricingSubSource",
    "fareReturned",
    "privateFareType",
    "itinTotalFare",
    "ptcFareBreakdowns",
    "divideInPartyInd"
})
public class AirItineraryPricingInfo
    implements Equals, ToString
{

    protected String pricingSource;
    protected String pricingSubSource;
    protected String fareReturned;
    protected String privateFareType;
    protected List<ItinTotalFare> itinTotalFare;
    @XmlElement(name = "pTC_FareBreakdowns")
    protected PTCFareBreakdowns ptcFareBreakdowns;
    protected String divideInPartyInd;

    /**
     * Gets the value of the pricingSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingSource() {
        return pricingSource;
    }

    /**
     * Sets the value of the pricingSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingSource(String value) {
        this.pricingSource = value;
    }

    /**
     * Gets the value of the pricingSubSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingSubSource() {
        return pricingSubSource;
    }

    /**
     * Sets the value of the pricingSubSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingSubSource(String value) {
        this.pricingSubSource = value;
    }

    /**
     * Gets the value of the fareReturned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareReturned() {
        return fareReturned;
    }

    /**
     * Sets the value of the fareReturned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareReturned(String value) {
        this.fareReturned = value;
    }

    /**
     * Gets the value of the privateFareType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateFareType() {
        return privateFareType;
    }

    /**
     * Sets the value of the privateFareType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateFareType(String value) {
        this.privateFareType = value;
    }

    /**
     * Gets the value of the itinTotalFare property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itinTotalFare property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItinTotalFare().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItinTotalFare }
     * 
     * 
     */
    public List<ItinTotalFare> getItinTotalFare() {
        if (itinTotalFare == null) {
            itinTotalFare = new ArrayList<ItinTotalFare>();
        }
        return this.itinTotalFare;
    }

    /**
     * Gets the value of the ptcFareBreakdowns property.
     * 
     * @return
     *     possible object is
     *     {@link PTCFareBreakdowns }
     *     
     */
    public PTCFareBreakdowns getPTCFareBreakdowns() {
        return ptcFareBreakdowns;
    }

    /**
     * Sets the value of the ptcFareBreakdowns property.
     * 
     * @param value
     *     allowed object is
     *     {@link PTCFareBreakdowns }
     *     
     */
    public void setPTCFareBreakdowns(PTCFareBreakdowns value) {
        this.ptcFareBreakdowns = value;
    }

    /**
     * Gets the value of the divideInPartyInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivideInPartyInd() {
        return divideInPartyInd;
    }

    /**
     * Sets the value of the divideInPartyInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivideInPartyInd(String value) {
        this.divideInPartyInd = value;
    }

    public void setItinTotalFare(List<ItinTotalFare> value) {
        this.itinTotalFare = null;
        List<ItinTotalFare> draftl = this.getItinTotalFare();
        draftl.addAll(value);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String thePricingSource;
            thePricingSource = this.getPricingSource();
            strategy.appendField(locator, this, "pricingSource", buffer, thePricingSource);
        }
        {
            String thePricingSubSource;
            thePricingSubSource = this.getPricingSubSource();
            strategy.appendField(locator, this, "pricingSubSource", buffer, thePricingSubSource);
        }
        {
            String theFareReturned;
            theFareReturned = this.getFareReturned();
            strategy.appendField(locator, this, "fareReturned", buffer, theFareReturned);
        }
        {
            String thePrivateFareType;
            thePrivateFareType = this.getPrivateFareType();
            strategy.appendField(locator, this, "privateFareType", buffer, thePrivateFareType);
        }
        {
            List<ItinTotalFare> theItinTotalFare;
            theItinTotalFare = (((this.itinTotalFare!= null)&&(!this.itinTotalFare.isEmpty()))?this.getItinTotalFare():null);
            strategy.appendField(locator, this, "itinTotalFare", buffer, theItinTotalFare);
        }
        {
            PTCFareBreakdowns thePTCFareBreakdowns;
            thePTCFareBreakdowns = this.getPTCFareBreakdowns();
            strategy.appendField(locator, this, "ptcFareBreakdowns", buffer, thePTCFareBreakdowns);
        }
        {
            String theDivideInPartyInd;
            theDivideInPartyInd = this.getDivideInPartyInd();
            strategy.appendField(locator, this, "divideInPartyInd", buffer, theDivideInPartyInd);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof AirItineraryPricingInfo)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final AirItineraryPricingInfo that = ((AirItineraryPricingInfo) object);
        {
            String lhsPricingSource;
            lhsPricingSource = this.getPricingSource();
            String rhsPricingSource;
            rhsPricingSource = that.getPricingSource();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "pricingSource", lhsPricingSource), LocatorUtils.property(thatLocator, "pricingSource", rhsPricingSource), lhsPricingSource, rhsPricingSource)) {
                return false;
            }
        }
        {
            String lhsPricingSubSource;
            lhsPricingSubSource = this.getPricingSubSource();
            String rhsPricingSubSource;
            rhsPricingSubSource = that.getPricingSubSource();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "pricingSubSource", lhsPricingSubSource), LocatorUtils.property(thatLocator, "pricingSubSource", rhsPricingSubSource), lhsPricingSubSource, rhsPricingSubSource)) {
                return false;
            }
        }
        {
            String lhsFareReturned;
            lhsFareReturned = this.getFareReturned();
            String rhsFareReturned;
            rhsFareReturned = that.getFareReturned();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fareReturned", lhsFareReturned), LocatorUtils.property(thatLocator, "fareReturned", rhsFareReturned), lhsFareReturned, rhsFareReturned)) {
                return false;
            }
        }
        {
            String lhsPrivateFareType;
            lhsPrivateFareType = this.getPrivateFareType();
            String rhsPrivateFareType;
            rhsPrivateFareType = that.getPrivateFareType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "privateFareType", lhsPrivateFareType), LocatorUtils.property(thatLocator, "privateFareType", rhsPrivateFareType), lhsPrivateFareType, rhsPrivateFareType)) {
                return false;
            }
        }
        {
            List<ItinTotalFare> lhsItinTotalFare;
            lhsItinTotalFare = (((this.itinTotalFare!= null)&&(!this.itinTotalFare.isEmpty()))?this.getItinTotalFare():null);
            List<ItinTotalFare> rhsItinTotalFare;
            rhsItinTotalFare = (((that.itinTotalFare!= null)&&(!that.itinTotalFare.isEmpty()))?that.getItinTotalFare():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "itinTotalFare", lhsItinTotalFare), LocatorUtils.property(thatLocator, "itinTotalFare", rhsItinTotalFare), lhsItinTotalFare, rhsItinTotalFare)) {
                return false;
            }
        }
        {
            PTCFareBreakdowns lhsPTCFareBreakdowns;
            lhsPTCFareBreakdowns = this.getPTCFareBreakdowns();
            PTCFareBreakdowns rhsPTCFareBreakdowns;
            rhsPTCFareBreakdowns = that.getPTCFareBreakdowns();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ptcFareBreakdowns", lhsPTCFareBreakdowns), LocatorUtils.property(thatLocator, "ptcFareBreakdowns", rhsPTCFareBreakdowns), lhsPTCFareBreakdowns, rhsPTCFareBreakdowns)) {
                return false;
            }
        }
        {
            String lhsDivideInPartyInd;
            lhsDivideInPartyInd = this.getDivideInPartyInd();
            String rhsDivideInPartyInd;
            rhsDivideInPartyInd = that.getDivideInPartyInd();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "divideInPartyInd", lhsDivideInPartyInd), LocatorUtils.property(thatLocator, "divideInPartyInd", rhsDivideInPartyInd), lhsDivideInPartyInd, rhsDivideInPartyInd)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

}
