//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for AirItinerary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AirItinerary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="directionInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="originDestinationOption" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}OriginDestinationOption" maxOccurs="50"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AirItinerary", propOrder = {
    "directionInd",
    "originDestinationOption"
})
public class AirItinerary
    implements Equals, ToString
{

    @XmlElement(required = true)
    protected String directionInd;
    @XmlElement(required = true)
    protected List<OriginDestinationOption> originDestinationOption;

    /**
     * Gets the value of the directionInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectionInd() {
        return directionInd;
    }

    /**
     * Sets the value of the directionInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectionInd(String value) {
        this.directionInd = value;
    }

    /**
     * Gets the value of the originDestinationOption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the originDestinationOption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginDestinationOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OriginDestinationOption }
     * 
     * 
     */
    public List<OriginDestinationOption> getOriginDestinationOption() {
        if (originDestinationOption == null) {
            originDestinationOption = new ArrayList<OriginDestinationOption>();
        }
        return this.originDestinationOption;
    }

    public void setOriginDestinationOption(List<OriginDestinationOption> value) {
        this.originDestinationOption = null;
        List<OriginDestinationOption> draftl = this.getOriginDestinationOption();
        draftl.addAll(value);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theDirectionInd;
            theDirectionInd = this.getDirectionInd();
            strategy.appendField(locator, this, "directionInd", buffer, theDirectionInd);
        }
        {
            List<OriginDestinationOption> theOriginDestinationOption;
            theOriginDestinationOption = (((this.originDestinationOption!= null)&&(!this.originDestinationOption.isEmpty()))?this.getOriginDestinationOption():null);
            strategy.appendField(locator, this, "originDestinationOption", buffer, theOriginDestinationOption);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof AirItinerary)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final AirItinerary that = ((AirItinerary) object);
        {
            String lhsDirectionInd;
            lhsDirectionInd = this.getDirectionInd();
            String rhsDirectionInd;
            rhsDirectionInd = that.getDirectionInd();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "directionInd", lhsDirectionInd), LocatorUtils.property(thatLocator, "directionInd", rhsDirectionInd), lhsDirectionInd, rhsDirectionInd)) {
                return false;
            }
        }
        {
            List<OriginDestinationOption> lhsOriginDestinationOption;
            lhsOriginDestinationOption = (((this.originDestinationOption!= null)&&(!this.originDestinationOption.isEmpty()))?this.getOriginDestinationOption():null);
            List<OriginDestinationOption> rhsOriginDestinationOption;
            rhsOriginDestinationOption = (((that.originDestinationOption!= null)&&(!that.originDestinationOption.isEmpty()))?that.getOriginDestinationOption():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "originDestinationOption", lhsOriginDestinationOption), LocatorUtils.property(thatLocator, "originDestinationOption", rhsOriginDestinationOption), lhsOriginDestinationOption, rhsOriginDestinationOption)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

}
