//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for BaggageInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaggageInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="segmentId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="allowance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaggageInformation", propOrder = {
    "segmentId",
    "allowance"
})
public class BaggageInformation
    implements Equals, ToString
{

    protected List<String> segmentId;
    protected String allowance;

    /**
     * Gets the value of the segmentId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segmentId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegmentId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSegmentId() {
        if (segmentId == null) {
            segmentId = new ArrayList<String>();
        }
        return this.segmentId;
    }

    /**
     * Gets the value of the allowance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowance() {
        return allowance;
    }

    /**
     * Sets the value of the allowance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowance(String value) {
        this.allowance = value;
    }

    public void setSegmentId(List<String> value) {
        this.segmentId = null;
        List<String> draftl = this.getSegmentId();
        draftl.addAll(value);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<String> theSegmentId;
            theSegmentId = (((this.segmentId!= null)&&(!this.segmentId.isEmpty()))?this.getSegmentId():null);
            strategy.appendField(locator, this, "segmentId", buffer, theSegmentId);
        }
        {
            String theAllowance;
            theAllowance = this.getAllowance();
            strategy.appendField(locator, this, "allowance", buffer, theAllowance);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof BaggageInformation)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final BaggageInformation that = ((BaggageInformation) object);
        {
            List<String> lhsSegmentId;
            lhsSegmentId = (((this.segmentId!= null)&&(!this.segmentId.isEmpty()))?this.getSegmentId():null);
            List<String> rhsSegmentId;
            rhsSegmentId = (((that.segmentId!= null)&&(!that.segmentId.isEmpty()))?that.getSegmentId():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "segmentId", lhsSegmentId), LocatorUtils.property(thatLocator, "segmentId", rhsSegmentId), lhsSegmentId, rhsSegmentId)) {
                return false;
            }
        }
        {
            String lhsAllowance;
            lhsAllowance = this.getAllowance();
            String rhsAllowance;
            rhsAllowance = that.getAllowance();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "allowance", lhsAllowance), LocatorUtils.property(thatLocator, "allowance", rhsAllowance), lhsAllowance, rhsAllowance)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

}
