//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for BaggageInformationList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaggageInformationList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="baggageInformation" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}BaggageInformation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaggageInformationList", propOrder = {
    "baggageInformation"
})
public class BaggageInformationList
    implements Equals, ToString
{

    protected List<BaggageInformation> baggageInformation;

    /**
     * Gets the value of the baggageInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baggageInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaggageInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BaggageInformation }
     * 
     * 
     */
    public List<BaggageInformation> getBaggageInformation() {
        if (baggageInformation == null) {
            baggageInformation = new ArrayList<BaggageInformation>();
        }
        return this.baggageInformation;
    }

    public void setBaggageInformation(List<BaggageInformation> value) {
        this.baggageInformation = null;
        List<BaggageInformation> draftl = this.getBaggageInformation();
        draftl.addAll(value);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<BaggageInformation> theBaggageInformation;
            theBaggageInformation = (((this.baggageInformation!= null)&&(!this.baggageInformation.isEmpty()))?this.getBaggageInformation():null);
            strategy.appendField(locator, this, "baggageInformation", buffer, theBaggageInformation);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof BaggageInformationList)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final BaggageInformationList that = ((BaggageInformationList) object);
        {
            List<BaggageInformation> lhsBaggageInformation;
            lhsBaggageInformation = (((this.baggageInformation!= null)&&(!this.baggageInformation.isEmpty()))?this.getBaggageInformation():null);
            List<BaggageInformation> rhsBaggageInformation;
            rhsBaggageInformation = (((that.baggageInformation!= null)&&(!that.baggageInformation.isEmpty()))?that.getBaggageInformation():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "baggageInformation", lhsBaggageInformation), LocatorUtils.property(thatLocator, "baggageInformation", rhsBaggageInformation), lhsBaggageInformation, rhsBaggageInformation)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

}
