//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for FlightSegment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightSegment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="departureDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrivalDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stopQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flightNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resBookDesigCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="elapsedTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="departureAirportLocationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrivalAirportLocationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="departureAirportTerminalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrivalAirportTerminalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="airEquipType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="operatingAirlineCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="operatingAirlineFlightNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="marketingAirlineCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="departureTimeZone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrivalTimeZone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eTicketInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originAirportCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="destinationAirportCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightSegment", propOrder = {
    "departureDateTime",
    "arrivalDateTime",
    "stopQuantity",
    "flightNumber",
    "resBookDesigCode",
    "elapsedTime",
    "departureAirportLocationCode",
    "arrivalAirportLocationCode",
    "departureAirportTerminalID",
    "arrivalAirportTerminalID",
    "airEquipType",
    "operatingAirlineCode",
    "operatingAirlineFlightNbr",
    "marketingAirlineCode",
    "departureTimeZone",
    "arrivalTimeZone",
    "eTicketInd",
    "originAirportCode",
    "destinationAirportCode"
})
public class FlightSegment
    implements Equals, ToString
{

    protected String departureDateTime;
    protected String arrivalDateTime;
    protected String stopQuantity;
    protected String flightNumber;
    protected String resBookDesigCode;
    protected String elapsedTime;
    protected String departureAirportLocationCode;
    protected String arrivalAirportLocationCode;
    protected String departureAirportTerminalID;
    protected String arrivalAirportTerminalID;
    protected String airEquipType;
    protected String operatingAirlineCode;
    protected String operatingAirlineFlightNbr;
    protected String marketingAirlineCode;
    protected String departureTimeZone;
    protected String arrivalTimeZone;
    protected String eTicketInd;
    protected String originAirportCode;
    protected String destinationAirportCode;

    /**
     * Gets the value of the departureDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureDateTime() {
        return departureDateTime;
    }

    /**
     * Sets the value of the departureDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureDateTime(String value) {
        this.departureDateTime = value;
    }

    /**
     * Gets the value of the arrivalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalDateTime() {
        return arrivalDateTime;
    }

    /**
     * Sets the value of the arrivalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalDateTime(String value) {
        this.arrivalDateTime = value;
    }

    /**
     * Gets the value of the stopQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopQuantity() {
        return stopQuantity;
    }

    /**
     * Sets the value of the stopQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopQuantity(String value) {
        this.stopQuantity = value;
    }

    /**
     * Gets the value of the flightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightNumber() {
        return flightNumber;
    }

    /**
     * Sets the value of the flightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightNumber(String value) {
        this.flightNumber = value;
    }

    /**
     * Gets the value of the resBookDesigCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResBookDesigCode() {
        return resBookDesigCode;
    }

    /**
     * Sets the value of the resBookDesigCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResBookDesigCode(String value) {
        this.resBookDesigCode = value;
    }

    /**
     * Gets the value of the elapsedTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElapsedTime() {
        return elapsedTime;
    }

    /**
     * Sets the value of the elapsedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElapsedTime(String value) {
        this.elapsedTime = value;
    }

    /**
     * Gets the value of the departureAirportLocationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureAirportLocationCode() {
        return departureAirportLocationCode;
    }

    /**
     * Sets the value of the departureAirportLocationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureAirportLocationCode(String value) {
        this.departureAirportLocationCode = value;
    }

    /**
     * Gets the value of the arrivalAirportLocationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalAirportLocationCode() {
        return arrivalAirportLocationCode;
    }

    /**
     * Sets the value of the arrivalAirportLocationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalAirportLocationCode(String value) {
        this.arrivalAirportLocationCode = value;
    }

    /**
     * Gets the value of the departureAirportTerminalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureAirportTerminalID() {
        return departureAirportTerminalID;
    }

    /**
     * Sets the value of the departureAirportTerminalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureAirportTerminalID(String value) {
        this.departureAirportTerminalID = value;
    }

    /**
     * Gets the value of the arrivalAirportTerminalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalAirportTerminalID() {
        return arrivalAirportTerminalID;
    }

    /**
     * Sets the value of the arrivalAirportTerminalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalAirportTerminalID(String value) {
        this.arrivalAirportTerminalID = value;
    }

    /**
     * Gets the value of the airEquipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirEquipType() {
        return airEquipType;
    }

    /**
     * Sets the value of the airEquipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirEquipType(String value) {
        this.airEquipType = value;
    }

    /**
     * Gets the value of the operatingAirlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatingAirlineCode() {
        return operatingAirlineCode;
    }

    /**
     * Sets the value of the operatingAirlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatingAirlineCode(String value) {
        this.operatingAirlineCode = value;
    }

    /**
     * Gets the value of the operatingAirlineFlightNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatingAirlineFlightNbr() {
        return operatingAirlineFlightNbr;
    }

    /**
     * Sets the value of the operatingAirlineFlightNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatingAirlineFlightNbr(String value) {
        this.operatingAirlineFlightNbr = value;
    }

    /**
     * Gets the value of the marketingAirlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketingAirlineCode() {
        return marketingAirlineCode;
    }

    /**
     * Sets the value of the marketingAirlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketingAirlineCode(String value) {
        this.marketingAirlineCode = value;
    }

    /**
     * Gets the value of the departureTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureTimeZone() {
        return departureTimeZone;
    }

    /**
     * Sets the value of the departureTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureTimeZone(String value) {
        this.departureTimeZone = value;
    }

    /**
     * Gets the value of the arrivalTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalTimeZone() {
        return arrivalTimeZone;
    }

    /**
     * Sets the value of the arrivalTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalTimeZone(String value) {
        this.arrivalTimeZone = value;
    }

    /**
     * Gets the value of the eTicketInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getETicketInd() {
        return eTicketInd;
    }

    /**
     * Sets the value of the eTicketInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setETicketInd(String value) {
        this.eTicketInd = value;
    }

    /**
     * Gets the value of the originAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginAirportCode() {
        return originAirportCode;
    }

    /**
     * Sets the value of the originAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginAirportCode(String value) {
        this.originAirportCode = value;
    }

    /**
     * Gets the value of the destinationAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationAirportCode() {
        return destinationAirportCode;
    }

    /**
     * Sets the value of the destinationAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationAirportCode(String value) {
        this.destinationAirportCode = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theDepartureDateTime;
            theDepartureDateTime = this.getDepartureDateTime();
            strategy.appendField(locator, this, "departureDateTime", buffer, theDepartureDateTime);
        }
        {
            String theArrivalDateTime;
            theArrivalDateTime = this.getArrivalDateTime();
            strategy.appendField(locator, this, "arrivalDateTime", buffer, theArrivalDateTime);
        }
        {
            String theStopQuantity;
            theStopQuantity = this.getStopQuantity();
            strategy.appendField(locator, this, "stopQuantity", buffer, theStopQuantity);
        }
        {
            String theFlightNumber;
            theFlightNumber = this.getFlightNumber();
            strategy.appendField(locator, this, "flightNumber", buffer, theFlightNumber);
        }
        {
            String theResBookDesigCode;
            theResBookDesigCode = this.getResBookDesigCode();
            strategy.appendField(locator, this, "resBookDesigCode", buffer, theResBookDesigCode);
        }
        {
            String theElapsedTime;
            theElapsedTime = this.getElapsedTime();
            strategy.appendField(locator, this, "elapsedTime", buffer, theElapsedTime);
        }
        {
            String theDepartureAirportLocationCode;
            theDepartureAirportLocationCode = this.getDepartureAirportLocationCode();
            strategy.appendField(locator, this, "departureAirportLocationCode", buffer, theDepartureAirportLocationCode);
        }
        {
            String theArrivalAirportLocationCode;
            theArrivalAirportLocationCode = this.getArrivalAirportLocationCode();
            strategy.appendField(locator, this, "arrivalAirportLocationCode", buffer, theArrivalAirportLocationCode);
        }
        {
            String theDepartureAirportTerminalID;
            theDepartureAirportTerminalID = this.getDepartureAirportTerminalID();
            strategy.appendField(locator, this, "departureAirportTerminalID", buffer, theDepartureAirportTerminalID);
        }
        {
            String theArrivalAirportTerminalID;
            theArrivalAirportTerminalID = this.getArrivalAirportTerminalID();
            strategy.appendField(locator, this, "arrivalAirportTerminalID", buffer, theArrivalAirportTerminalID);
        }
        {
            String theAirEquipType;
            theAirEquipType = this.getAirEquipType();
            strategy.appendField(locator, this, "airEquipType", buffer, theAirEquipType);
        }
        {
            String theOperatingAirlineCode;
            theOperatingAirlineCode = this.getOperatingAirlineCode();
            strategy.appendField(locator, this, "operatingAirlineCode", buffer, theOperatingAirlineCode);
        }
        {
            String theOperatingAirlineFlightNbr;
            theOperatingAirlineFlightNbr = this.getOperatingAirlineFlightNbr();
            strategy.appendField(locator, this, "operatingAirlineFlightNbr", buffer, theOperatingAirlineFlightNbr);
        }
        {
            String theMarketingAirlineCode;
            theMarketingAirlineCode = this.getMarketingAirlineCode();
            strategy.appendField(locator, this, "marketingAirlineCode", buffer, theMarketingAirlineCode);
        }
        {
            String theDepartureTimeZone;
            theDepartureTimeZone = this.getDepartureTimeZone();
            strategy.appendField(locator, this, "departureTimeZone", buffer, theDepartureTimeZone);
        }
        {
            String theArrivalTimeZone;
            theArrivalTimeZone = this.getArrivalTimeZone();
            strategy.appendField(locator, this, "arrivalTimeZone", buffer, theArrivalTimeZone);
        }
        {
            String theETicketInd;
            theETicketInd = this.getETicketInd();
            strategy.appendField(locator, this, "eTicketInd", buffer, theETicketInd);
        }
        {
            String theOriginAirportCode;
            theOriginAirportCode = this.getOriginAirportCode();
            strategy.appendField(locator, this, "originAirportCode", buffer, theOriginAirportCode);
        }
        {
            String theDestinationAirportCode;
            theDestinationAirportCode = this.getDestinationAirportCode();
            strategy.appendField(locator, this, "destinationAirportCode", buffer, theDestinationAirportCode);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof FlightSegment)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final FlightSegment that = ((FlightSegment) object);
        {
            String lhsDepartureDateTime;
            lhsDepartureDateTime = this.getDepartureDateTime();
            String rhsDepartureDateTime;
            rhsDepartureDateTime = that.getDepartureDateTime();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "departureDateTime", lhsDepartureDateTime), LocatorUtils.property(thatLocator, "departureDateTime", rhsDepartureDateTime), lhsDepartureDateTime, rhsDepartureDateTime)) {
                return false;
            }
        }
        {
            String lhsArrivalDateTime;
            lhsArrivalDateTime = this.getArrivalDateTime();
            String rhsArrivalDateTime;
            rhsArrivalDateTime = that.getArrivalDateTime();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "arrivalDateTime", lhsArrivalDateTime), LocatorUtils.property(thatLocator, "arrivalDateTime", rhsArrivalDateTime), lhsArrivalDateTime, rhsArrivalDateTime)) {
                return false;
            }
        }
        {
            String lhsStopQuantity;
            lhsStopQuantity = this.getStopQuantity();
            String rhsStopQuantity;
            rhsStopQuantity = that.getStopQuantity();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "stopQuantity", lhsStopQuantity), LocatorUtils.property(thatLocator, "stopQuantity", rhsStopQuantity), lhsStopQuantity, rhsStopQuantity)) {
                return false;
            }
        }
        {
            String lhsFlightNumber;
            lhsFlightNumber = this.getFlightNumber();
            String rhsFlightNumber;
            rhsFlightNumber = that.getFlightNumber();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "flightNumber", lhsFlightNumber), LocatorUtils.property(thatLocator, "flightNumber", rhsFlightNumber), lhsFlightNumber, rhsFlightNumber)) {
                return false;
            }
        }
        {
            String lhsResBookDesigCode;
            lhsResBookDesigCode = this.getResBookDesigCode();
            String rhsResBookDesigCode;
            rhsResBookDesigCode = that.getResBookDesigCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "resBookDesigCode", lhsResBookDesigCode), LocatorUtils.property(thatLocator, "resBookDesigCode", rhsResBookDesigCode), lhsResBookDesigCode, rhsResBookDesigCode)) {
                return false;
            }
        }
        {
            String lhsElapsedTime;
            lhsElapsedTime = this.getElapsedTime();
            String rhsElapsedTime;
            rhsElapsedTime = that.getElapsedTime();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "elapsedTime", lhsElapsedTime), LocatorUtils.property(thatLocator, "elapsedTime", rhsElapsedTime), lhsElapsedTime, rhsElapsedTime)) {
                return false;
            }
        }
        {
            String lhsDepartureAirportLocationCode;
            lhsDepartureAirportLocationCode = this.getDepartureAirportLocationCode();
            String rhsDepartureAirportLocationCode;
            rhsDepartureAirportLocationCode = that.getDepartureAirportLocationCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "departureAirportLocationCode", lhsDepartureAirportLocationCode), LocatorUtils.property(thatLocator, "departureAirportLocationCode", rhsDepartureAirportLocationCode), lhsDepartureAirportLocationCode, rhsDepartureAirportLocationCode)) {
                return false;
            }
        }
        {
            String lhsArrivalAirportLocationCode;
            lhsArrivalAirportLocationCode = this.getArrivalAirportLocationCode();
            String rhsArrivalAirportLocationCode;
            rhsArrivalAirportLocationCode = that.getArrivalAirportLocationCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "arrivalAirportLocationCode", lhsArrivalAirportLocationCode), LocatorUtils.property(thatLocator, "arrivalAirportLocationCode", rhsArrivalAirportLocationCode), lhsArrivalAirportLocationCode, rhsArrivalAirportLocationCode)) {
                return false;
            }
        }
        {
            String lhsDepartureAirportTerminalID;
            lhsDepartureAirportTerminalID = this.getDepartureAirportTerminalID();
            String rhsDepartureAirportTerminalID;
            rhsDepartureAirportTerminalID = that.getDepartureAirportTerminalID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "departureAirportTerminalID", lhsDepartureAirportTerminalID), LocatorUtils.property(thatLocator, "departureAirportTerminalID", rhsDepartureAirportTerminalID), lhsDepartureAirportTerminalID, rhsDepartureAirportTerminalID)) {
                return false;
            }
        }
        {
            String lhsArrivalAirportTerminalID;
            lhsArrivalAirportTerminalID = this.getArrivalAirportTerminalID();
            String rhsArrivalAirportTerminalID;
            rhsArrivalAirportTerminalID = that.getArrivalAirportTerminalID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "arrivalAirportTerminalID", lhsArrivalAirportTerminalID), LocatorUtils.property(thatLocator, "arrivalAirportTerminalID", rhsArrivalAirportTerminalID), lhsArrivalAirportTerminalID, rhsArrivalAirportTerminalID)) {
                return false;
            }
        }
        {
            String lhsAirEquipType;
            lhsAirEquipType = this.getAirEquipType();
            String rhsAirEquipType;
            rhsAirEquipType = that.getAirEquipType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "airEquipType", lhsAirEquipType), LocatorUtils.property(thatLocator, "airEquipType", rhsAirEquipType), lhsAirEquipType, rhsAirEquipType)) {
                return false;
            }
        }
        {
            String lhsOperatingAirlineCode;
            lhsOperatingAirlineCode = this.getOperatingAirlineCode();
            String rhsOperatingAirlineCode;
            rhsOperatingAirlineCode = that.getOperatingAirlineCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "operatingAirlineCode", lhsOperatingAirlineCode), LocatorUtils.property(thatLocator, "operatingAirlineCode", rhsOperatingAirlineCode), lhsOperatingAirlineCode, rhsOperatingAirlineCode)) {
                return false;
            }
        }
        {
            String lhsOperatingAirlineFlightNbr;
            lhsOperatingAirlineFlightNbr = this.getOperatingAirlineFlightNbr();
            String rhsOperatingAirlineFlightNbr;
            rhsOperatingAirlineFlightNbr = that.getOperatingAirlineFlightNbr();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "operatingAirlineFlightNbr", lhsOperatingAirlineFlightNbr), LocatorUtils.property(thatLocator, "operatingAirlineFlightNbr", rhsOperatingAirlineFlightNbr), lhsOperatingAirlineFlightNbr, rhsOperatingAirlineFlightNbr)) {
                return false;
            }
        }
        {
            String lhsMarketingAirlineCode;
            lhsMarketingAirlineCode = this.getMarketingAirlineCode();
            String rhsMarketingAirlineCode;
            rhsMarketingAirlineCode = that.getMarketingAirlineCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "marketingAirlineCode", lhsMarketingAirlineCode), LocatorUtils.property(thatLocator, "marketingAirlineCode", rhsMarketingAirlineCode), lhsMarketingAirlineCode, rhsMarketingAirlineCode)) {
                return false;
            }
        }
        {
            String lhsDepartureTimeZone;
            lhsDepartureTimeZone = this.getDepartureTimeZone();
            String rhsDepartureTimeZone;
            rhsDepartureTimeZone = that.getDepartureTimeZone();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "departureTimeZone", lhsDepartureTimeZone), LocatorUtils.property(thatLocator, "departureTimeZone", rhsDepartureTimeZone), lhsDepartureTimeZone, rhsDepartureTimeZone)) {
                return false;
            }
        }
        {
            String lhsArrivalTimeZone;
            lhsArrivalTimeZone = this.getArrivalTimeZone();
            String rhsArrivalTimeZone;
            rhsArrivalTimeZone = that.getArrivalTimeZone();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "arrivalTimeZone", lhsArrivalTimeZone), LocatorUtils.property(thatLocator, "arrivalTimeZone", rhsArrivalTimeZone), lhsArrivalTimeZone, rhsArrivalTimeZone)) {
                return false;
            }
        }
        {
            String lhsETicketInd;
            lhsETicketInd = this.getETicketInd();
            String rhsETicketInd;
            rhsETicketInd = that.getETicketInd();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "eTicketInd", lhsETicketInd), LocatorUtils.property(thatLocator, "eTicketInd", rhsETicketInd), lhsETicketInd, rhsETicketInd)) {
                return false;
            }
        }
        {
            String lhsOriginAirportCode;
            lhsOriginAirportCode = this.getOriginAirportCode();
            String rhsOriginAirportCode;
            rhsOriginAirportCode = that.getOriginAirportCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "originAirportCode", lhsOriginAirportCode), LocatorUtils.property(thatLocator, "originAirportCode", rhsOriginAirportCode), lhsOriginAirportCode, rhsOriginAirportCode)) {
                return false;
            }
        }
        {
            String lhsDestinationAirportCode;
            lhsDestinationAirportCode = this.getDestinationAirportCode();
            String rhsDestinationAirportCode;
            rhsDestinationAirportCode = that.getDestinationAirportCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "destinationAirportCode", lhsDestinationAirportCode), LocatorUtils.property(thatLocator, "destinationAirportCode", rhsDestinationAirportCode), lhsDestinationAirportCode, rhsDestinationAirportCode)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

}
