//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ItinTotalFare complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItinTotalFare">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BaseFareAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BaseFareCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BaseFareDecimalPlaces" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FareConstructionAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FareConstructionCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FareConstructionDecimalPlaces" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EquivFareAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EquivFareCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EquivFareDecimalPlaces" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxDecimalPlaces" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalFareAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalFareCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalFareDecimalPlaces" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItinTotalFare", propOrder = {
    "baseFareAmount",
    "baseFareCurrencyCode",
    "baseFareDecimalPlaces",
    "fareConstructionAmount",
    "fareConstructionCurrencyCode",
    "fareConstructionDecimalPlaces",
    "equivFareAmount",
    "equivFareCurrencyCode",
    "equivFareDecimalPlaces",
    "taxCode",
    "taxAmount",
    "taxCurrencyCode",
    "taxDecimalPlaces",
    "totalFareAmount",
    "totalFareCurrencyCode",
    "totalFareDecimalPlaces"
})
public class ItinTotalFare
    implements Equals, ToString
{

    @XmlElement(name = "BaseFareAmount")
    protected String baseFareAmount;
    @XmlElement(name = "BaseFareCurrencyCode")
    protected String baseFareCurrencyCode;
    @XmlElement(name = "BaseFareDecimalPlaces")
    protected String baseFareDecimalPlaces;
    @XmlElement(name = "FareConstructionAmount")
    protected String fareConstructionAmount;
    @XmlElement(name = "FareConstructionCurrencyCode")
    protected String fareConstructionCurrencyCode;
    @XmlElement(name = "FareConstructionDecimalPlaces")
    protected String fareConstructionDecimalPlaces;
    @XmlElement(name = "EquivFareAmount")
    protected String equivFareAmount;
    @XmlElement(name = "EquivFareCurrencyCode")
    protected String equivFareCurrencyCode;
    @XmlElement(name = "EquivFareDecimalPlaces")
    protected String equivFareDecimalPlaces;
    @XmlElement(name = "TaxCode")
    protected String taxCode;
    @XmlElement(name = "TaxAmount")
    protected String taxAmount;
    @XmlElement(name = "TaxCurrencyCode")
    protected String taxCurrencyCode;
    @XmlElement(name = "TaxDecimalPlaces")
    protected String taxDecimalPlaces;
    @XmlElement(name = "TotalFareAmount")
    protected String totalFareAmount;
    @XmlElement(name = "TotalFareCurrencyCode")
    protected String totalFareCurrencyCode;
    @XmlElement(name = "TotalFareDecimalPlaces")
    protected String totalFareDecimalPlaces;

    /**
     * Gets the value of the baseFareAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseFareAmount() {
        return baseFareAmount;
    }

    /**
     * Sets the value of the baseFareAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseFareAmount(String value) {
        this.baseFareAmount = value;
    }

    /**
     * Gets the value of the baseFareCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseFareCurrencyCode() {
        return baseFareCurrencyCode;
    }

    /**
     * Sets the value of the baseFareCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseFareCurrencyCode(String value) {
        this.baseFareCurrencyCode = value;
    }

    /**
     * Gets the value of the baseFareDecimalPlaces property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseFareDecimalPlaces() {
        return baseFareDecimalPlaces;
    }

    /**
     * Sets the value of the baseFareDecimalPlaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseFareDecimalPlaces(String value) {
        this.baseFareDecimalPlaces = value;
    }

    /**
     * Gets the value of the fareConstructionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareConstructionAmount() {
        return fareConstructionAmount;
    }

    /**
     * Sets the value of the fareConstructionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareConstructionAmount(String value) {
        this.fareConstructionAmount = value;
    }

    /**
     * Gets the value of the fareConstructionCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareConstructionCurrencyCode() {
        return fareConstructionCurrencyCode;
    }

    /**
     * Sets the value of the fareConstructionCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareConstructionCurrencyCode(String value) {
        this.fareConstructionCurrencyCode = value;
    }

    /**
     * Gets the value of the fareConstructionDecimalPlaces property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareConstructionDecimalPlaces() {
        return fareConstructionDecimalPlaces;
    }

    /**
     * Sets the value of the fareConstructionDecimalPlaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareConstructionDecimalPlaces(String value) {
        this.fareConstructionDecimalPlaces = value;
    }

    /**
     * Gets the value of the equivFareAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquivFareAmount() {
        return equivFareAmount;
    }

    /**
     * Sets the value of the equivFareAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquivFareAmount(String value) {
        this.equivFareAmount = value;
    }

    /**
     * Gets the value of the equivFareCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquivFareCurrencyCode() {
        return equivFareCurrencyCode;
    }

    /**
     * Sets the value of the equivFareCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquivFareCurrencyCode(String value) {
        this.equivFareCurrencyCode = value;
    }

    /**
     * Gets the value of the equivFareDecimalPlaces property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquivFareDecimalPlaces() {
        return equivFareDecimalPlaces;
    }

    /**
     * Sets the value of the equivFareDecimalPlaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquivFareDecimalPlaces(String value) {
        this.equivFareDecimalPlaces = value;
    }

    /**
     * Gets the value of the taxCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxCode() {
        return taxCode;
    }

    /**
     * Sets the value of the taxCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxCode(String value) {
        this.taxCode = value;
    }

    /**
     * Gets the value of the taxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAmount() {
        return taxAmount;
    }

    /**
     * Sets the value of the taxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAmount(String value) {
        this.taxAmount = value;
    }

    /**
     * Gets the value of the taxCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxCurrencyCode() {
        return taxCurrencyCode;
    }

    /**
     * Sets the value of the taxCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxCurrencyCode(String value) {
        this.taxCurrencyCode = value;
    }

    /**
     * Gets the value of the taxDecimalPlaces property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxDecimalPlaces() {
        return taxDecimalPlaces;
    }

    /**
     * Sets the value of the taxDecimalPlaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxDecimalPlaces(String value) {
        this.taxDecimalPlaces = value;
    }

    /**
     * Gets the value of the totalFareAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalFareAmount() {
        return totalFareAmount;
    }

    /**
     * Sets the value of the totalFareAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalFareAmount(String value) {
        this.totalFareAmount = value;
    }

    /**
     * Gets the value of the totalFareCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalFareCurrencyCode() {
        return totalFareCurrencyCode;
    }

    /**
     * Sets the value of the totalFareCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalFareCurrencyCode(String value) {
        this.totalFareCurrencyCode = value;
    }

    /**
     * Gets the value of the totalFareDecimalPlaces property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalFareDecimalPlaces() {
        return totalFareDecimalPlaces;
    }

    /**
     * Sets the value of the totalFareDecimalPlaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalFareDecimalPlaces(String value) {
        this.totalFareDecimalPlaces = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theBaseFareAmount;
            theBaseFareAmount = this.getBaseFareAmount();
            strategy.appendField(locator, this, "baseFareAmount", buffer, theBaseFareAmount);
        }
        {
            String theBaseFareCurrencyCode;
            theBaseFareCurrencyCode = this.getBaseFareCurrencyCode();
            strategy.appendField(locator, this, "baseFareCurrencyCode", buffer, theBaseFareCurrencyCode);
        }
        {
            String theBaseFareDecimalPlaces;
            theBaseFareDecimalPlaces = this.getBaseFareDecimalPlaces();
            strategy.appendField(locator, this, "baseFareDecimalPlaces", buffer, theBaseFareDecimalPlaces);
        }
        {
            String theFareConstructionAmount;
            theFareConstructionAmount = this.getFareConstructionAmount();
            strategy.appendField(locator, this, "fareConstructionAmount", buffer, theFareConstructionAmount);
        }
        {
            String theFareConstructionCurrencyCode;
            theFareConstructionCurrencyCode = this.getFareConstructionCurrencyCode();
            strategy.appendField(locator, this, "fareConstructionCurrencyCode", buffer, theFareConstructionCurrencyCode);
        }
        {
            String theFareConstructionDecimalPlaces;
            theFareConstructionDecimalPlaces = this.getFareConstructionDecimalPlaces();
            strategy.appendField(locator, this, "fareConstructionDecimalPlaces", buffer, theFareConstructionDecimalPlaces);
        }
        {
            String theEquivFareAmount;
            theEquivFareAmount = this.getEquivFareAmount();
            strategy.appendField(locator, this, "equivFareAmount", buffer, theEquivFareAmount);
        }
        {
            String theEquivFareCurrencyCode;
            theEquivFareCurrencyCode = this.getEquivFareCurrencyCode();
            strategy.appendField(locator, this, "equivFareCurrencyCode", buffer, theEquivFareCurrencyCode);
        }
        {
            String theEquivFareDecimalPlaces;
            theEquivFareDecimalPlaces = this.getEquivFareDecimalPlaces();
            strategy.appendField(locator, this, "equivFareDecimalPlaces", buffer, theEquivFareDecimalPlaces);
        }
        {
            String theTaxCode;
            theTaxCode = this.getTaxCode();
            strategy.appendField(locator, this, "taxCode", buffer, theTaxCode);
        }
        {
            String theTaxAmount;
            theTaxAmount = this.getTaxAmount();
            strategy.appendField(locator, this, "taxAmount", buffer, theTaxAmount);
        }
        {
            String theTaxCurrencyCode;
            theTaxCurrencyCode = this.getTaxCurrencyCode();
            strategy.appendField(locator, this, "taxCurrencyCode", buffer, theTaxCurrencyCode);
        }
        {
            String theTaxDecimalPlaces;
            theTaxDecimalPlaces = this.getTaxDecimalPlaces();
            strategy.appendField(locator, this, "taxDecimalPlaces", buffer, theTaxDecimalPlaces);
        }
        {
            String theTotalFareAmount;
            theTotalFareAmount = this.getTotalFareAmount();
            strategy.appendField(locator, this, "totalFareAmount", buffer, theTotalFareAmount);
        }
        {
            String theTotalFareCurrencyCode;
            theTotalFareCurrencyCode = this.getTotalFareCurrencyCode();
            strategy.appendField(locator, this, "totalFareCurrencyCode", buffer, theTotalFareCurrencyCode);
        }
        {
            String theTotalFareDecimalPlaces;
            theTotalFareDecimalPlaces = this.getTotalFareDecimalPlaces();
            strategy.appendField(locator, this, "totalFareDecimalPlaces", buffer, theTotalFareDecimalPlaces);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ItinTotalFare)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ItinTotalFare that = ((ItinTotalFare) object);
        {
            String lhsBaseFareAmount;
            lhsBaseFareAmount = this.getBaseFareAmount();
            String rhsBaseFareAmount;
            rhsBaseFareAmount = that.getBaseFareAmount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "baseFareAmount", lhsBaseFareAmount), LocatorUtils.property(thatLocator, "baseFareAmount", rhsBaseFareAmount), lhsBaseFareAmount, rhsBaseFareAmount)) {
                return false;
            }
        }
        {
            String lhsBaseFareCurrencyCode;
            lhsBaseFareCurrencyCode = this.getBaseFareCurrencyCode();
            String rhsBaseFareCurrencyCode;
            rhsBaseFareCurrencyCode = that.getBaseFareCurrencyCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "baseFareCurrencyCode", lhsBaseFareCurrencyCode), LocatorUtils.property(thatLocator, "baseFareCurrencyCode", rhsBaseFareCurrencyCode), lhsBaseFareCurrencyCode, rhsBaseFareCurrencyCode)) {
                return false;
            }
        }
        {
            String lhsBaseFareDecimalPlaces;
            lhsBaseFareDecimalPlaces = this.getBaseFareDecimalPlaces();
            String rhsBaseFareDecimalPlaces;
            rhsBaseFareDecimalPlaces = that.getBaseFareDecimalPlaces();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "baseFareDecimalPlaces", lhsBaseFareDecimalPlaces), LocatorUtils.property(thatLocator, "baseFareDecimalPlaces", rhsBaseFareDecimalPlaces), lhsBaseFareDecimalPlaces, rhsBaseFareDecimalPlaces)) {
                return false;
            }
        }
        {
            String lhsFareConstructionAmount;
            lhsFareConstructionAmount = this.getFareConstructionAmount();
            String rhsFareConstructionAmount;
            rhsFareConstructionAmount = that.getFareConstructionAmount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fareConstructionAmount", lhsFareConstructionAmount), LocatorUtils.property(thatLocator, "fareConstructionAmount", rhsFareConstructionAmount), lhsFareConstructionAmount, rhsFareConstructionAmount)) {
                return false;
            }
        }
        {
            String lhsFareConstructionCurrencyCode;
            lhsFareConstructionCurrencyCode = this.getFareConstructionCurrencyCode();
            String rhsFareConstructionCurrencyCode;
            rhsFareConstructionCurrencyCode = that.getFareConstructionCurrencyCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fareConstructionCurrencyCode", lhsFareConstructionCurrencyCode), LocatorUtils.property(thatLocator, "fareConstructionCurrencyCode", rhsFareConstructionCurrencyCode), lhsFareConstructionCurrencyCode, rhsFareConstructionCurrencyCode)) {
                return false;
            }
        }
        {
            String lhsFareConstructionDecimalPlaces;
            lhsFareConstructionDecimalPlaces = this.getFareConstructionDecimalPlaces();
            String rhsFareConstructionDecimalPlaces;
            rhsFareConstructionDecimalPlaces = that.getFareConstructionDecimalPlaces();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fareConstructionDecimalPlaces", lhsFareConstructionDecimalPlaces), LocatorUtils.property(thatLocator, "fareConstructionDecimalPlaces", rhsFareConstructionDecimalPlaces), lhsFareConstructionDecimalPlaces, rhsFareConstructionDecimalPlaces)) {
                return false;
            }
        }
        {
            String lhsEquivFareAmount;
            lhsEquivFareAmount = this.getEquivFareAmount();
            String rhsEquivFareAmount;
            rhsEquivFareAmount = that.getEquivFareAmount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "equivFareAmount", lhsEquivFareAmount), LocatorUtils.property(thatLocator, "equivFareAmount", rhsEquivFareAmount), lhsEquivFareAmount, rhsEquivFareAmount)) {
                return false;
            }
        }
        {
            String lhsEquivFareCurrencyCode;
            lhsEquivFareCurrencyCode = this.getEquivFareCurrencyCode();
            String rhsEquivFareCurrencyCode;
            rhsEquivFareCurrencyCode = that.getEquivFareCurrencyCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "equivFareCurrencyCode", lhsEquivFareCurrencyCode), LocatorUtils.property(thatLocator, "equivFareCurrencyCode", rhsEquivFareCurrencyCode), lhsEquivFareCurrencyCode, rhsEquivFareCurrencyCode)) {
                return false;
            }
        }
        {
            String lhsEquivFareDecimalPlaces;
            lhsEquivFareDecimalPlaces = this.getEquivFareDecimalPlaces();
            String rhsEquivFareDecimalPlaces;
            rhsEquivFareDecimalPlaces = that.getEquivFareDecimalPlaces();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "equivFareDecimalPlaces", lhsEquivFareDecimalPlaces), LocatorUtils.property(thatLocator, "equivFareDecimalPlaces", rhsEquivFareDecimalPlaces), lhsEquivFareDecimalPlaces, rhsEquivFareDecimalPlaces)) {
                return false;
            }
        }
        {
            String lhsTaxCode;
            lhsTaxCode = this.getTaxCode();
            String rhsTaxCode;
            rhsTaxCode = that.getTaxCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxCode", lhsTaxCode), LocatorUtils.property(thatLocator, "taxCode", rhsTaxCode), lhsTaxCode, rhsTaxCode)) {
                return false;
            }
        }
        {
            String lhsTaxAmount;
            lhsTaxAmount = this.getTaxAmount();
            String rhsTaxAmount;
            rhsTaxAmount = that.getTaxAmount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxAmount", lhsTaxAmount), LocatorUtils.property(thatLocator, "taxAmount", rhsTaxAmount), lhsTaxAmount, rhsTaxAmount)) {
                return false;
            }
        }
        {
            String lhsTaxCurrencyCode;
            lhsTaxCurrencyCode = this.getTaxCurrencyCode();
            String rhsTaxCurrencyCode;
            rhsTaxCurrencyCode = that.getTaxCurrencyCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxCurrencyCode", lhsTaxCurrencyCode), LocatorUtils.property(thatLocator, "taxCurrencyCode", rhsTaxCurrencyCode), lhsTaxCurrencyCode, rhsTaxCurrencyCode)) {
                return false;
            }
        }
        {
            String lhsTaxDecimalPlaces;
            lhsTaxDecimalPlaces = this.getTaxDecimalPlaces();
            String rhsTaxDecimalPlaces;
            rhsTaxDecimalPlaces = that.getTaxDecimalPlaces();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxDecimalPlaces", lhsTaxDecimalPlaces), LocatorUtils.property(thatLocator, "taxDecimalPlaces", rhsTaxDecimalPlaces), lhsTaxDecimalPlaces, rhsTaxDecimalPlaces)) {
                return false;
            }
        }
        {
            String lhsTotalFareAmount;
            lhsTotalFareAmount = this.getTotalFareAmount();
            String rhsTotalFareAmount;
            rhsTotalFareAmount = that.getTotalFareAmount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalFareAmount", lhsTotalFareAmount), LocatorUtils.property(thatLocator, "totalFareAmount", rhsTotalFareAmount), lhsTotalFareAmount, rhsTotalFareAmount)) {
                return false;
            }
        }
        {
            String lhsTotalFareCurrencyCode;
            lhsTotalFareCurrencyCode = this.getTotalFareCurrencyCode();
            String rhsTotalFareCurrencyCode;
            rhsTotalFareCurrencyCode = that.getTotalFareCurrencyCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalFareCurrencyCode", lhsTotalFareCurrencyCode), LocatorUtils.property(thatLocator, "totalFareCurrencyCode", rhsTotalFareCurrencyCode), lhsTotalFareCurrencyCode, rhsTotalFareCurrencyCode)) {
                return false;
            }
        }
        {
            String lhsTotalFareDecimalPlaces;
            lhsTotalFareDecimalPlaces = this.getTotalFareDecimalPlaces();
            String rhsTotalFareDecimalPlaces;
            rhsTotalFareDecimalPlaces = that.getTotalFareDecimalPlaces();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalFareDecimalPlaces", lhsTotalFareDecimalPlaces), LocatorUtils.property(thatLocator, "totalFareDecimalPlaces", rhsTotalFareDecimalPlaces), lhsTotalFareDecimalPlaces, rhsTotalFareDecimalPlaces)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

}
