//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.skandha.eim.air.jaxb.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.skandha.eim.air.jaxb.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItinTotalFare }
     * 
     */
    public ItinTotalFare createItinTotalFare() {
        return new ItinTotalFare();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link TravelerInfoSummary }
     * 
     */
    public TravelerInfoSummary createTravelerInfoSummary() {
        return new TravelerInfoSummary();
    }

    /**
     * Create an instance of {@link PTCFareBreakdowns }
     * 
     */
    public PTCFareBreakdowns createPTCFareBreakdowns() {
        return new PTCFareBreakdowns();
    }

    /**
     * Create an instance of {@link FareInfos }
     * 
     */
    public FareInfos createFareInfos() {
        return new FareInfos();
    }

    /**
     * Create an instance of {@link BaggageInformationList }
     * 
     */
    public BaggageInformationList createBaggageInformationList() {
        return new BaggageInformationList();
    }

    /**
     * Create an instance of {@link FareBasisCode }
     * 
     */
    public FareBasisCode createFareBasisCode() {
        return new FareBasisCode();
    }

    /**
     * Create an instance of {@link BaggageInformation }
     * 
     */
    public BaggageInformation createBaggageInformation() {
        return new BaggageInformation();
    }

    /**
     * Create an instance of {@link TravelPreferences }
     * 
     */
    public TravelPreferences createTravelPreferences() {
        return new TravelPreferences();
    }

    /**
     * Create an instance of {@link PTCFareBreakdown }
     * 
     */
    public PTCFareBreakdown createPTCFareBreakdown() {
        return new PTCFareBreakdown();
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link Surcharges }
     * 
     */
    public Surcharges createSurcharges() {
        return new Surcharges();
    }

    /**
     * Create an instance of {@link AirLowFareSearchRQ }
     * 
     */
    public AirLowFareSearchRQ createAirLowFareSearchRQ() {
        return new AirLowFareSearchRQ();
    }

    /**
     * Create an instance of {@link TicketingInfo }
     * 
     */
    public TicketingInfo createTicketingInfo() {
        return new TicketingInfo();
    }

    /**
     * Create an instance of {@link AirItineraryPricingInfo }
     * 
     */
    public AirItineraryPricingInfo createAirItineraryPricingInfo() {
        return new AirItineraryPricingInfo();
    }

    /**
     * Create an instance of {@link FareInfo }
     * 
     */
    public FareInfo createFareInfo() {
        return new FareInfo();
    }

    /**
     * Create an instance of {@link RequesterDetails }
     * 
     */
    public RequesterDetails createRequesterDetails() {
        return new RequesterDetails();
    }

    /**
     * Create an instance of {@link PricedItineraries }
     * 
     */
    public PricedItineraries createPricedItineraries() {
        return new PricedItineraries();
    }

    /**
     * Create an instance of {@link Tax }
     * 
     */
    public Tax createTax() {
        return new Tax();
    }

    /**
     * Create an instance of {@link PricedItinerary }
     * 
     */
    public PricedItinerary createPricedItinerary() {
        return new PricedItinerary();
    }

    /**
     * Create an instance of {@link PassengerFare }
     * 
     */
    public PassengerFare createPassengerFare() {
        return new PassengerFare();
    }

    /**
     * Create an instance of {@link OriginDestinationOption }
     * 
     */
    public OriginDestinationOption createOriginDestinationOption() {
        return new OriginDestinationOption();
    }

    /**
     * Create an instance of {@link Taxes }
     * 
     */
    public Taxes createTaxes() {
        return new Taxes();
    }

    /**
     * Create an instance of {@link OriginDestinationInformation }
     * 
     */
    public OriginDestinationInformation createOriginDestinationInformation() {
        return new OriginDestinationInformation();
    }

    /**
     * Create an instance of {@link AirItinerary }
     * 
     */
    public AirItinerary createAirItinerary() {
        return new AirItinerary();
    }

    /**
     * Create an instance of {@link TPAExtensions }
     * 
     */
    public TPAExtensions createTPAExtensions() {
        return new TPAExtensions();
    }

    /**
     * Create an instance of {@link FlightSegment }
     * 
     */
    public FlightSegment createFlightSegment() {
        return new FlightSegment();
    }

    /**
     * Create an instance of {@link AirLowFareSearchRS }
     * 
     */
    public AirLowFareSearchRS createAirLowFareSearchRS() {
        return new AirLowFareSearchRS();
    }

    /**
     * Create an instance of {@link FareBasisCodes }
     * 
     */
    public FareBasisCodes createFareBasisCodes() {
        return new FareBasisCodes();
    }

}
