//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for OriginDestinationOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OriginDestinationOption">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="elapsedTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flightSegment" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}FlightSegment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginDestinationOption", propOrder = {
    "elapsedTime",
    "flightSegment"
})
public class OriginDestinationOption
    implements Equals, ToString
{

    protected String elapsedTime;
    protected List<FlightSegment> flightSegment;

    /**
     * Gets the value of the elapsedTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElapsedTime() {
        return elapsedTime;
    }

    /**
     * Sets the value of the elapsedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElapsedTime(String value) {
        this.elapsedTime = value;
    }

    /**
     * Gets the value of the flightSegment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flightSegment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlightSegment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightSegment }
     * 
     * 
     */
    public List<FlightSegment> getFlightSegment() {
        if (flightSegment == null) {
            flightSegment = new ArrayList<FlightSegment>();
        }
        return this.flightSegment;
    }

    public void setFlightSegment(List<FlightSegment> value) {
        this.flightSegment = null;
        List<FlightSegment> draftl = this.getFlightSegment();
        draftl.addAll(value);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theElapsedTime;
            theElapsedTime = this.getElapsedTime();
            strategy.appendField(locator, this, "elapsedTime", buffer, theElapsedTime);
        }
        {
            List<FlightSegment> theFlightSegment;
            theFlightSegment = (((this.flightSegment!= null)&&(!this.flightSegment.isEmpty()))?this.getFlightSegment():null);
            strategy.appendField(locator, this, "flightSegment", buffer, theFlightSegment);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof OriginDestinationOption)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final OriginDestinationOption that = ((OriginDestinationOption) object);
        {
            String lhsElapsedTime;
            lhsElapsedTime = this.getElapsedTime();
            String rhsElapsedTime;
            rhsElapsedTime = that.getElapsedTime();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "elapsedTime", lhsElapsedTime), LocatorUtils.property(thatLocator, "elapsedTime", rhsElapsedTime), lhsElapsedTime, rhsElapsedTime)) {
                return false;
            }
        }
        {
            List<FlightSegment> lhsFlightSegment;
            lhsFlightSegment = (((this.flightSegment!= null)&&(!this.flightSegment.isEmpty()))?this.getFlightSegment():null);
            List<FlightSegment> rhsFlightSegment;
            rhsFlightSegment = (((that.flightSegment!= null)&&(!that.flightSegment.isEmpty()))?that.getFlightSegment():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "flightSegment", lhsFlightSegment), LocatorUtils.property(thatLocator, "flightSegment", rhsFlightSegment), lhsFlightSegment, rhsFlightSegment)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

}
