//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.skandha.eim.air.jaxb.v1;
