//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for PricedItinerary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PricedItinerary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sequenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="airItinerary" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}AirItinerary" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="airItineraryPricingInfo" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}AirItineraryPricingInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ticketingInfo" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}TicketingInfo" minOccurs="0"/>
 *         &lt;element name="tPA_Extensions" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}TPA_Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PricedItinerary", propOrder = {
    "sequenceNumber",
    "airItinerary",
    "airItineraryPricingInfo",
    "ticketingInfo",
    "tpaExtensions"
})
public class PricedItinerary
    implements Equals, ToString
{

    protected String sequenceNumber;
    protected List<AirItinerary> airItinerary;
    protected List<AirItineraryPricingInfo> airItineraryPricingInfo;
    protected TicketingInfo ticketingInfo;
    @XmlElement(name = "tPA_Extensions")
    protected TPAExtensions tpaExtensions;

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceNumber(String value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the airItinerary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the airItinerary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAirItinerary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AirItinerary }
     * 
     * 
     */
    public List<AirItinerary> getAirItinerary() {
        if (airItinerary == null) {
            airItinerary = new ArrayList<AirItinerary>();
        }
        return this.airItinerary;
    }

    /**
     * Gets the value of the airItineraryPricingInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the airItineraryPricingInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAirItineraryPricingInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AirItineraryPricingInfo }
     * 
     * 
     */
    public List<AirItineraryPricingInfo> getAirItineraryPricingInfo() {
        if (airItineraryPricingInfo == null) {
            airItineraryPricingInfo = new ArrayList<AirItineraryPricingInfo>();
        }
        return this.airItineraryPricingInfo;
    }

    /**
     * Gets the value of the ticketingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TicketingInfo }
     *     
     */
    public TicketingInfo getTicketingInfo() {
        return ticketingInfo;
    }

    /**
     * Sets the value of the ticketingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketingInfo }
     *     
     */
    public void setTicketingInfo(TicketingInfo value) {
        this.ticketingInfo = value;
    }

    /**
     * Gets the value of the tpaExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link TPAExtensions }
     *     
     */
    public TPAExtensions getTPAExtensions() {
        return tpaExtensions;
    }

    /**
     * Sets the value of the tpaExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPAExtensions }
     *     
     */
    public void setTPAExtensions(TPAExtensions value) {
        this.tpaExtensions = value;
    }

    public void setAirItinerary(List<AirItinerary> value) {
        this.airItinerary = null;
        List<AirItinerary> draftl = this.getAirItinerary();
        draftl.addAll(value);
    }

    public void setAirItineraryPricingInfo(List<AirItineraryPricingInfo> value) {
        this.airItineraryPricingInfo = null;
        List<AirItineraryPricingInfo> draftl = this.getAirItineraryPricingInfo();
        draftl.addAll(value);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theSequenceNumber;
            theSequenceNumber = this.getSequenceNumber();
            strategy.appendField(locator, this, "sequenceNumber", buffer, theSequenceNumber);
        }
        {
            List<AirItinerary> theAirItinerary;
            theAirItinerary = (((this.airItinerary!= null)&&(!this.airItinerary.isEmpty()))?this.getAirItinerary():null);
            strategy.appendField(locator, this, "airItinerary", buffer, theAirItinerary);
        }
        {
            List<AirItineraryPricingInfo> theAirItineraryPricingInfo;
            theAirItineraryPricingInfo = (((this.airItineraryPricingInfo!= null)&&(!this.airItineraryPricingInfo.isEmpty()))?this.getAirItineraryPricingInfo():null);
            strategy.appendField(locator, this, "airItineraryPricingInfo", buffer, theAirItineraryPricingInfo);
        }
        {
            TicketingInfo theTicketingInfo;
            theTicketingInfo = this.getTicketingInfo();
            strategy.appendField(locator, this, "ticketingInfo", buffer, theTicketingInfo);
        }
        {
            TPAExtensions theTPAExtensions;
            theTPAExtensions = this.getTPAExtensions();
            strategy.appendField(locator, this, "tpaExtensions", buffer, theTPAExtensions);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof PricedItinerary)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final PricedItinerary that = ((PricedItinerary) object);
        {
            String lhsSequenceNumber;
            lhsSequenceNumber = this.getSequenceNumber();
            String rhsSequenceNumber;
            rhsSequenceNumber = that.getSequenceNumber();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "sequenceNumber", lhsSequenceNumber), LocatorUtils.property(thatLocator, "sequenceNumber", rhsSequenceNumber), lhsSequenceNumber, rhsSequenceNumber)) {
                return false;
            }
        }
        {
            List<AirItinerary> lhsAirItinerary;
            lhsAirItinerary = (((this.airItinerary!= null)&&(!this.airItinerary.isEmpty()))?this.getAirItinerary():null);
            List<AirItinerary> rhsAirItinerary;
            rhsAirItinerary = (((that.airItinerary!= null)&&(!that.airItinerary.isEmpty()))?that.getAirItinerary():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "airItinerary", lhsAirItinerary), LocatorUtils.property(thatLocator, "airItinerary", rhsAirItinerary), lhsAirItinerary, rhsAirItinerary)) {
                return false;
            }
        }
        {
            List<AirItineraryPricingInfo> lhsAirItineraryPricingInfo;
            lhsAirItineraryPricingInfo = (((this.airItineraryPricingInfo!= null)&&(!this.airItineraryPricingInfo.isEmpty()))?this.getAirItineraryPricingInfo():null);
            List<AirItineraryPricingInfo> rhsAirItineraryPricingInfo;
            rhsAirItineraryPricingInfo = (((that.airItineraryPricingInfo!= null)&&(!that.airItineraryPricingInfo.isEmpty()))?that.getAirItineraryPricingInfo():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "airItineraryPricingInfo", lhsAirItineraryPricingInfo), LocatorUtils.property(thatLocator, "airItineraryPricingInfo", rhsAirItineraryPricingInfo), lhsAirItineraryPricingInfo, rhsAirItineraryPricingInfo)) {
                return false;
            }
        }
        {
            TicketingInfo lhsTicketingInfo;
            lhsTicketingInfo = this.getTicketingInfo();
            TicketingInfo rhsTicketingInfo;
            rhsTicketingInfo = that.getTicketingInfo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ticketingInfo", lhsTicketingInfo), LocatorUtils.property(thatLocator, "ticketingInfo", rhsTicketingInfo), lhsTicketingInfo, rhsTicketingInfo)) {
                return false;
            }
        }
        {
            TPAExtensions lhsTPAExtensions;
            lhsTPAExtensions = this.getTPAExtensions();
            TPAExtensions rhsTPAExtensions;
            rhsTPAExtensions = that.getTPAExtensions();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "tpaExtensions", lhsTPAExtensions), LocatorUtils.property(thatLocator, "tpaExtensions", rhsTPAExtensions), lhsTPAExtensions, rhsTPAExtensions)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

}
