//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for PTC_FareBreakdowns complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PTC_FareBreakdowns">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ptc_FareBreakdown" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}PTC_FareBreakdown" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PTC_FareBreakdowns", propOrder = {
    "ptcFareBreakdown"
})
public class PTCFareBreakdowns
    implements Equals, ToString
{

    @XmlElement(name = "ptc_FareBreakdown")
    protected List<PTCFareBreakdown> ptcFareBreakdown;

    /**
     * Gets the value of the ptcFareBreakdown property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ptcFareBreakdown property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPtcFareBreakdown().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PTCFareBreakdown }
     * 
     * 
     */
    public List<PTCFareBreakdown> getPtcFareBreakdown() {
        if (ptcFareBreakdown == null) {
            ptcFareBreakdown = new ArrayList<PTCFareBreakdown>();
        }
        return this.ptcFareBreakdown;
    }

    public void setPtcFareBreakdown(List<PTCFareBreakdown> value) {
        this.ptcFareBreakdown = null;
        List<PTCFareBreakdown> draftl = this.getPtcFareBreakdown();
        draftl.addAll(value);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<PTCFareBreakdown> thePtcFareBreakdown;
            thePtcFareBreakdown = (((this.ptcFareBreakdown!= null)&&(!this.ptcFareBreakdown.isEmpty()))?this.getPtcFareBreakdown():null);
            strategy.appendField(locator, this, "ptcFareBreakdown", buffer, thePtcFareBreakdown);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof PTCFareBreakdowns)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final PTCFareBreakdowns that = ((PTCFareBreakdowns) object);
        {
            List<PTCFareBreakdown> lhsPtcFareBreakdown;
            lhsPtcFareBreakdown = (((this.ptcFareBreakdown!= null)&&(!this.ptcFareBreakdown.isEmpty()))?this.getPtcFareBreakdown():null);
            List<PTCFareBreakdown> rhsPtcFareBreakdown;
            rhsPtcFareBreakdown = (((that.ptcFareBreakdown!= null)&&(!that.ptcFareBreakdown.isEmpty()))?that.getPtcFareBreakdown():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ptcFareBreakdown", lhsPtcFareBreakdown), LocatorUtils.property(thatLocator, "ptcFareBreakdown", rhsPtcFareBreakdown), lhsPtcFareBreakdown, rhsPtcFareBreakdown)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

}
