//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for Surcharges complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Surcharges">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="surcharges" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="surchargesInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="surchargesType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Surcharges", propOrder = {
    "surcharges",
    "surchargesInd",
    "surchargesType"
})
public class Surcharges
    implements Equals, ToString
{

    protected String surcharges;
    protected String surchargesInd;
    protected String surchargesType;

    /**
     * Gets the value of the surcharges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurcharges() {
        return surcharges;
    }

    /**
     * Sets the value of the surcharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurcharges(String value) {
        this.surcharges = value;
    }

    /**
     * Gets the value of the surchargesInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurchargesInd() {
        return surchargesInd;
    }

    /**
     * Sets the value of the surchargesInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurchargesInd(String value) {
        this.surchargesInd = value;
    }

    /**
     * Gets the value of the surchargesType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurchargesType() {
        return surchargesType;
    }

    /**
     * Sets the value of the surchargesType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurchargesType(String value) {
        this.surchargesType = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theSurcharges;
            theSurcharges = this.getSurcharges();
            strategy.appendField(locator, this, "surcharges", buffer, theSurcharges);
        }
        {
            String theSurchargesInd;
            theSurchargesInd = this.getSurchargesInd();
            strategy.appendField(locator, this, "surchargesInd", buffer, theSurchargesInd);
        }
        {
            String theSurchargesType;
            theSurchargesType = this.getSurchargesType();
            strategy.appendField(locator, this, "surchargesType", buffer, theSurchargesType);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Surcharges)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Surcharges that = ((Surcharges) object);
        {
            String lhsSurcharges;
            lhsSurcharges = this.getSurcharges();
            String rhsSurcharges;
            rhsSurcharges = that.getSurcharges();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "surcharges", lhsSurcharges), LocatorUtils.property(thatLocator, "surcharges", rhsSurcharges), lhsSurcharges, rhsSurcharges)) {
                return false;
            }
        }
        {
            String lhsSurchargesInd;
            lhsSurchargesInd = this.getSurchargesInd();
            String rhsSurchargesInd;
            rhsSurchargesInd = that.getSurchargesInd();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "surchargesInd", lhsSurchargesInd), LocatorUtils.property(thatLocator, "surchargesInd", rhsSurchargesInd), lhsSurchargesInd, rhsSurchargesInd)) {
                return false;
            }
        }
        {
            String lhsSurchargesType;
            lhsSurchargesType = this.getSurchargesType();
            String rhsSurchargesType;
            rhsSurchargesType = that.getSurchargesType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "surchargesType", lhsSurchargesType), LocatorUtils.property(thatLocator, "surchargesType", rhsSurchargesType), lhsSurchargesType, rhsSurchargesType)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

}
