//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for TPA_Extensions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPA_Extensions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="validatingCarrierCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eTicket" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPA_Extensions", propOrder = {
    "validatingCarrierCode",
    "eTicket"
})
public class TPAExtensions
    implements Equals, ToString
{

    protected String validatingCarrierCode;
    protected String eTicket;

    /**
     * Gets the value of the validatingCarrierCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidatingCarrierCode() {
        return validatingCarrierCode;
    }

    /**
     * Sets the value of the validatingCarrierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidatingCarrierCode(String value) {
        this.validatingCarrierCode = value;
    }

    /**
     * Gets the value of the eTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getETicket() {
        return eTicket;
    }

    /**
     * Sets the value of the eTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setETicket(String value) {
        this.eTicket = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theValidatingCarrierCode;
            theValidatingCarrierCode = this.getValidatingCarrierCode();
            strategy.appendField(locator, this, "validatingCarrierCode", buffer, theValidatingCarrierCode);
        }
        {
            String theETicket;
            theETicket = this.getETicket();
            strategy.appendField(locator, this, "eTicket", buffer, theETicket);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TPAExtensions)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final TPAExtensions that = ((TPAExtensions) object);
        {
            String lhsValidatingCarrierCode;
            lhsValidatingCarrierCode = this.getValidatingCarrierCode();
            String rhsValidatingCarrierCode;
            rhsValidatingCarrierCode = that.getValidatingCarrierCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "validatingCarrierCode", lhsValidatingCarrierCode), LocatorUtils.property(thatLocator, "validatingCarrierCode", rhsValidatingCarrierCode), lhsValidatingCarrierCode, rhsValidatingCarrierCode)) {
                return false;
            }
        }
        {
            String lhsETicket;
            lhsETicket = this.getETicket();
            String rhsETicket;
            rhsETicket = that.getETicket();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "eTicket", lhsETicket), LocatorUtils.property(thatLocator, "eTicket", rhsETicket), lhsETicket, rhsETicket)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

}
