//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 10:02:03 PM IST 
//


package com.skandha.eim.air.jaxb.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for TravelerInfoSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TravelerInfoSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seatsRequested" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="passengerTypeQuantity" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="4"/>
 *         &lt;element name="pricePriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="directFlightsPriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timePriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vendorPriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specificPTC_Indicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TravelerInfoSummary", propOrder = {
    "seatsRequested",
    "passengerTypeQuantity",
    "pricePriority",
    "directFlightsPriority",
    "timePriority",
    "vendorPriority",
    "specificPTCIndicator"
})
public class TravelerInfoSummary
    implements Equals, ToString
{

    protected String seatsRequested;
    @XmlElement(required = true)
    protected List<String> passengerTypeQuantity;
    protected String pricePriority;
    protected String directFlightsPriority;
    protected String timePriority;
    protected String vendorPriority;
    @XmlElement(name = "specificPTC_Indicator")
    protected String specificPTCIndicator;

    /**
     * Gets the value of the seatsRequested property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatsRequested() {
        return seatsRequested;
    }

    /**
     * Sets the value of the seatsRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatsRequested(String value) {
        this.seatsRequested = value;
    }

    /**
     * Gets the value of the passengerTypeQuantity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passengerTypeQuantity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassengerTypeQuantity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPassengerTypeQuantity() {
        if (passengerTypeQuantity == null) {
            passengerTypeQuantity = new ArrayList<String>();
        }
        return this.passengerTypeQuantity;
    }

    /**
     * Gets the value of the pricePriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricePriority() {
        return pricePriority;
    }

    /**
     * Sets the value of the pricePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricePriority(String value) {
        this.pricePriority = value;
    }

    /**
     * Gets the value of the directFlightsPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectFlightsPriority() {
        return directFlightsPriority;
    }

    /**
     * Sets the value of the directFlightsPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectFlightsPriority(String value) {
        this.directFlightsPriority = value;
    }

    /**
     * Gets the value of the timePriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimePriority() {
        return timePriority;
    }

    /**
     * Sets the value of the timePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimePriority(String value) {
        this.timePriority = value;
    }

    /**
     * Gets the value of the vendorPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorPriority() {
        return vendorPriority;
    }

    /**
     * Sets the value of the vendorPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorPriority(String value) {
        this.vendorPriority = value;
    }

    /**
     * Gets the value of the specificPTCIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificPTCIndicator() {
        return specificPTCIndicator;
    }

    /**
     * Sets the value of the specificPTCIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificPTCIndicator(String value) {
        this.specificPTCIndicator = value;
    }

    public void setPassengerTypeQuantity(List<String> value) {
        this.passengerTypeQuantity = null;
        List<String> draftl = this.getPassengerTypeQuantity();
        draftl.addAll(value);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theSeatsRequested;
            theSeatsRequested = this.getSeatsRequested();
            strategy.appendField(locator, this, "seatsRequested", buffer, theSeatsRequested);
        }
        {
            List<String> thePassengerTypeQuantity;
            thePassengerTypeQuantity = (((this.passengerTypeQuantity!= null)&&(!this.passengerTypeQuantity.isEmpty()))?this.getPassengerTypeQuantity():null);
            strategy.appendField(locator, this, "passengerTypeQuantity", buffer, thePassengerTypeQuantity);
        }
        {
            String thePricePriority;
            thePricePriority = this.getPricePriority();
            strategy.appendField(locator, this, "pricePriority", buffer, thePricePriority);
        }
        {
            String theDirectFlightsPriority;
            theDirectFlightsPriority = this.getDirectFlightsPriority();
            strategy.appendField(locator, this, "directFlightsPriority", buffer, theDirectFlightsPriority);
        }
        {
            String theTimePriority;
            theTimePriority = this.getTimePriority();
            strategy.appendField(locator, this, "timePriority", buffer, theTimePriority);
        }
        {
            String theVendorPriority;
            theVendorPriority = this.getVendorPriority();
            strategy.appendField(locator, this, "vendorPriority", buffer, theVendorPriority);
        }
        {
            String theSpecificPTCIndicator;
            theSpecificPTCIndicator = this.getSpecificPTCIndicator();
            strategy.appendField(locator, this, "specificPTCIndicator", buffer, theSpecificPTCIndicator);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TravelerInfoSummary)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final TravelerInfoSummary that = ((TravelerInfoSummary) object);
        {
            String lhsSeatsRequested;
            lhsSeatsRequested = this.getSeatsRequested();
            String rhsSeatsRequested;
            rhsSeatsRequested = that.getSeatsRequested();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "seatsRequested", lhsSeatsRequested), LocatorUtils.property(thatLocator, "seatsRequested", rhsSeatsRequested), lhsSeatsRequested, rhsSeatsRequested)) {
                return false;
            }
        }
        {
            List<String> lhsPassengerTypeQuantity;
            lhsPassengerTypeQuantity = (((this.passengerTypeQuantity!= null)&&(!this.passengerTypeQuantity.isEmpty()))?this.getPassengerTypeQuantity():null);
            List<String> rhsPassengerTypeQuantity;
            rhsPassengerTypeQuantity = (((that.passengerTypeQuantity!= null)&&(!that.passengerTypeQuantity.isEmpty()))?that.getPassengerTypeQuantity():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "passengerTypeQuantity", lhsPassengerTypeQuantity), LocatorUtils.property(thatLocator, "passengerTypeQuantity", rhsPassengerTypeQuantity), lhsPassengerTypeQuantity, rhsPassengerTypeQuantity)) {
                return false;
            }
        }
        {
            String lhsPricePriority;
            lhsPricePriority = this.getPricePriority();
            String rhsPricePriority;
            rhsPricePriority = that.getPricePriority();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "pricePriority", lhsPricePriority), LocatorUtils.property(thatLocator, "pricePriority", rhsPricePriority), lhsPricePriority, rhsPricePriority)) {
                return false;
            }
        }
        {
            String lhsDirectFlightsPriority;
            lhsDirectFlightsPriority = this.getDirectFlightsPriority();
            String rhsDirectFlightsPriority;
            rhsDirectFlightsPriority = that.getDirectFlightsPriority();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "directFlightsPriority", lhsDirectFlightsPriority), LocatorUtils.property(thatLocator, "directFlightsPriority", rhsDirectFlightsPriority), lhsDirectFlightsPriority, rhsDirectFlightsPriority)) {
                return false;
            }
        }
        {
            String lhsTimePriority;
            lhsTimePriority = this.getTimePriority();
            String rhsTimePriority;
            rhsTimePriority = that.getTimePriority();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "timePriority", lhsTimePriority), LocatorUtils.property(thatLocator, "timePriority", rhsTimePriority), lhsTimePriority, rhsTimePriority)) {
                return false;
            }
        }
        {
            String lhsVendorPriority;
            lhsVendorPriority = this.getVendorPriority();
            String rhsVendorPriority;
            rhsVendorPriority = that.getVendorPriority();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "vendorPriority", lhsVendorPriority), LocatorUtils.property(thatLocator, "vendorPriority", rhsVendorPriority), lhsVendorPriority, rhsVendorPriority)) {
                return false;
            }
        }
        {
            String lhsSpecificPTCIndicator;
            lhsSpecificPTCIndicator = this.getSpecificPTCIndicator();
            String rhsSpecificPTCIndicator;
            rhsSpecificPTCIndicator = that.getSpecificPTCIndicator();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "specificPTCIndicator", lhsSpecificPTCIndicator), LocatorUtils.property(thatLocator, "specificPTCIndicator", rhsSpecificPTCIndicator), lhsSpecificPTCIndicator, rhsSpecificPTCIndicator)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

}
