//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 10:01:58 AM IST 
//


package com.skandha.eim.air.jaxb.v2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requesterDetails" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}RequesterDetails" minOccurs="0"/>
 *         &lt;element name="originDestinationInformation" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}OriginDestinationInformation" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="travelPreferences" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}TravelPreferences" maxOccurs="unbounded"/>
 *         &lt;element name="travelerInfoSummary" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}TravelerInfoSummary" maxOccurs="unbounded"/>
 *         &lt;element name="tpaextensions" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}TPA_Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requesterDetails",
    "originDestinationInformation",
    "travelPreferences",
    "travelerInfoSummary",
    "tpaextensions"
})
@XmlRootElement(name = "AirLowFareSearchRQ")
public class AirLowFareSearchRQ {

    protected RequesterDetails requesterDetails;
    protected List<OriginDestinationInformation> originDestinationInformation;
    @XmlElement(required = true)
    protected List<TravelPreferences> travelPreferences;
    @XmlElement(required = true)
    protected List<TravelerInfoSummary> travelerInfoSummary;
    protected TPAExtensions tpaextensions;

    /**
     * Gets the value of the requesterDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RequesterDetails }
     *     
     */
    public RequesterDetails getRequesterDetails() {
        return requesterDetails;
    }

    /**
     * Sets the value of the requesterDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequesterDetails }
     *     
     */
    public void setRequesterDetails(RequesterDetails value) {
        this.requesterDetails = value;
    }

    /**
     * Gets the value of the originDestinationInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the originDestinationInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginDestinationInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OriginDestinationInformation }
     * 
     * 
     */
    public List<OriginDestinationInformation> getOriginDestinationInformation() {
        if (originDestinationInformation == null) {
            originDestinationInformation = new ArrayList<OriginDestinationInformation>();
        }
        return this.originDestinationInformation;
    }

    /**
     * Gets the value of the travelPreferences property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the travelPreferences property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTravelPreferences().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TravelPreferences }
     * 
     * 
     */
    public List<TravelPreferences> getTravelPreferences() {
        if (travelPreferences == null) {
            travelPreferences = new ArrayList<TravelPreferences>();
        }
        return this.travelPreferences;
    }

    /**
     * Gets the value of the travelerInfoSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the travelerInfoSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTravelerInfoSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TravelerInfoSummary }
     * 
     * 
     */
    public List<TravelerInfoSummary> getTravelerInfoSummary() {
        if (travelerInfoSummary == null) {
            travelerInfoSummary = new ArrayList<TravelerInfoSummary>();
        }
        return this.travelerInfoSummary;
    }

    /**
     * Gets the value of the tpaextensions property.
     * 
     * @return
     *     possible object is
     *     {@link TPAExtensions }
     *     
     */
    public TPAExtensions getTpaextensions() {
        return tpaextensions;
    }

    /**
     * Sets the value of the tpaextensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPAExtensions }
     *     
     */
    public void setTpaextensions(TPAExtensions value) {
        this.tpaextensions = value;
    }

}
