//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 10:01:58 AM IST 
//


package com.skandha.eim.air.jaxb.v2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.skandha.eim.air.jaxb.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.skandha.eim.air.jaxb.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AirLowFareSearchRQ }
     * 
     */
    public AirLowFareSearchRQ createAirLowFareSearchRQ() {
        return new AirLowFareSearchRQ();
    }

    /**
     * Create an instance of {@link RequesterDetails }
     * 
     */
    public RequesterDetails createRequesterDetails() {
        return new RequesterDetails();
    }

    /**
     * Create an instance of {@link OriginDestinationInformation }
     * 
     */
    public OriginDestinationInformation createOriginDestinationInformation() {
        return new OriginDestinationInformation();
    }

    /**
     * Create an instance of {@link TravelPreferences }
     * 
     */
    public TravelPreferences createTravelPreferences() {
        return new TravelPreferences();
    }

    /**
     * Create an instance of {@link TravelerInfoSummary }
     * 
     */
    public TravelerInfoSummary createTravelerInfoSummary() {
        return new TravelerInfoSummary();
    }

    /**
     * Create an instance of {@link TPAExtensions }
     * 
     */
    public TPAExtensions createTPAExtensions() {
        return new TPAExtensions();
    }

}
