//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 10:01:58 AM IST 
//


package com.skandha.eim.air.jaxb.v2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TravelerInfoSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TravelerInfoSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="seatsRequested" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="passengerTypeQuantity" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="4"/>
 *         &lt;element name="pricePriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="directFlightsPriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timePriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vendorPriority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specificPTC_Indicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TravelerInfoSummary", propOrder = {
    "seatsRequested",
    "passengerTypeQuantity",
    "pricePriority",
    "directFlightsPriority",
    "timePriority",
    "vendorPriority",
    "specificPTCIndicator"
})
public class TravelerInfoSummary {

    protected String seatsRequested;
    @XmlElement(required = true)
    protected List<String> passengerTypeQuantity;
    protected String pricePriority;
    protected String directFlightsPriority;
    protected String timePriority;
    protected String vendorPriority;
    @XmlElement(name = "specificPTC_Indicator")
    protected String specificPTCIndicator;

    /**
     * Gets the value of the seatsRequested property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatsRequested() {
        return seatsRequested;
    }

    /**
     * Sets the value of the seatsRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatsRequested(String value) {
        this.seatsRequested = value;
    }

    /**
     * Gets the value of the passengerTypeQuantity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passengerTypeQuantity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassengerTypeQuantity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPassengerTypeQuantity() {
        if (passengerTypeQuantity == null) {
            passengerTypeQuantity = new ArrayList<String>();
        }
        return this.passengerTypeQuantity;
    }

    /**
     * Gets the value of the pricePriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricePriority() {
        return pricePriority;
    }

    /**
     * Sets the value of the pricePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricePriority(String value) {
        this.pricePriority = value;
    }

    /**
     * Gets the value of the directFlightsPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectFlightsPriority() {
        return directFlightsPriority;
    }

    /**
     * Sets the value of the directFlightsPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectFlightsPriority(String value) {
        this.directFlightsPriority = value;
    }

    /**
     * Gets the value of the timePriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimePriority() {
        return timePriority;
    }

    /**
     * Sets the value of the timePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimePriority(String value) {
        this.timePriority = value;
    }

    /**
     * Gets the value of the vendorPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorPriority() {
        return vendorPriority;
    }

    /**
     * Sets the value of the vendorPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorPriority(String value) {
        this.vendorPriority = value;
    }

    /**
     * Gets the value of the specificPTCIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificPTCIndicator() {
        return specificPTCIndicator;
    }

    /**
     * Sets the value of the specificPTCIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificPTCIndicator(String value) {
        this.specificPTCIndicator = value;
    }

}
