//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 10:01:58 AM IST 
//


package com.skandha.eim.air.jaxb.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TravelPreferences complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TravelPreferences">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flightTypePref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cabinPref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eTicketDesired" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="validInterlineTicket" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="xoFares" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TravelPreferences", propOrder = {
    "flightTypePref",
    "cabinPref",
    "eTicketDesired",
    "validInterlineTicket",
    "xoFares"
})
public class TravelPreferences {

    protected String flightTypePref;
    protected String cabinPref;
    protected String eTicketDesired;
    protected String validInterlineTicket;
    protected String xoFares;

    /**
     * Gets the value of the flightTypePref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightTypePref() {
        return flightTypePref;
    }

    /**
     * Sets the value of the flightTypePref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightTypePref(String value) {
        this.flightTypePref = value;
    }

    /**
     * Gets the value of the cabinPref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCabinPref() {
        return cabinPref;
    }

    /**
     * Sets the value of the cabinPref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCabinPref(String value) {
        this.cabinPref = value;
    }

    /**
     * Gets the value of the eTicketDesired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getETicketDesired() {
        return eTicketDesired;
    }

    /**
     * Sets the value of the eTicketDesired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setETicketDesired(String value) {
        this.eTicketDesired = value;
    }

    /**
     * Gets the value of the validInterlineTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidInterlineTicket() {
        return validInterlineTicket;
    }

    /**
     * Sets the value of the validInterlineTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidInterlineTicket(String value) {
        this.validInterlineTicket = value;
    }

    /**
     * Gets the value of the xoFares property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXoFares() {
        return xoFares;
    }

    /**
     * Sets the value of the xoFares property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXoFares(String value) {
        this.xoFares = value;
    }

}
