//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 09:24:00 PM IST 
//


package com.skandha.eim.air.jaxb.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requesterDetails" type="{http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/}RequesterDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requesterDetails"
})
@XmlRootElement(name = "AirLowFareSearchRQ")
public class AirLowFareSearchRQ {

    protected RequesterDetails requesterDetails;

    /**
     * Gets the value of the requesterDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RequesterDetails }
     *     
     */
    public RequesterDetails getRequesterDetails() {
        return requesterDetails;
    }

    /**
     * Sets the value of the requesterDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequesterDetails }
     *     
     */
    public void setRequesterDetails(RequesterDetails value) {
        this.requesterDetails = value;
    }

}
