//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 09:24:00 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.xmlns.skandha.com/datatypes/Air/Service/1.0/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.skandha.eim.air.jaxb.v3;
